<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>PixJoin.Core.Tests</RootNamespace>
    <AssemblyName>PixJoin.Core.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.IO" />
    <Using Include="System.Windows" />
    <Using Include="System.Windows.Media" />
    <Using Include="System.Windows.Media.Imaging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PixJoin.Core\PixJoin.Core.csproj" />
  </ItemGroup>

</Project>
